from pydantic import BaseModel
class simulation(BaseModel):
    size: int
    percentage_alc_only: float
    percentage_dep_only: float 
    percentage_tobacco_only: float
    percentage_alc_dep: float
    percentage_alc_tobacco: float
    percentage_dep_tobacco: float 
    percentage_tobacco_alcoholism_depression: float
    treatment_noth: float
    treatment_1_conditions: float
    treatment_2_conditions: float
    treatment_3_conditions: float
    gender: list[float]
    bmi: list[float]
    edu: list[float]
    seed: int
    age: list[float]